Convert carousel css to tailwindcss
PUP-The-Programmers-Guild/TPGWebsite pull request #20
Opened 2023-06-11 17:12 UTC by Karmotrine

- convert carousel css to tailwindcss
- remove unused module.css (about, hero-carousel, page)
- add mockdataImage.ts for carousel mock data
- add "picsum.photos" for image domain

2023-06-11 18:21 UTC, Lemon1903 commented on src/mock/mockdataImage.ts
> +    id: number;
`id` not used

2023-06-11 20:03 UTC, Lemon1903 commented on src/components/Home/Hero/ShowcaseCarousel.tsx
> +  const heroSlider = "flex items-center justify-center text-[50px] text-white font-medium min-w-[459.35px] min-h-[424.48px] max-h-[459.35px]"
I think this should be placed directly on the HTML element it should contain. Having one long line with tailwind is inevitable I guess if it really have many styles in it.

2023-06-11 20:03 UTC, Lemon1903 commented on src/components/Home/News/index.tsx
> +  const numberSlide = "flex items-center justify-center text-[50px] text-black font-medium min-h-[271px] min-w-[339px] max-h-[339px]"
Same reason above

2023-06-11 20:04 UTC, Lemon1903 commented
The code is running well and the carousels is working well already. My question is that the `ShowcaseCarousel` really looks like this? Or should it fill the whole container?
![image](https://github.com/PUP-The-Programmers-Guild/TPGWebsite/assets/99325731/8d5385e2-8551-4b18-a9c8-a684dca19595)

I have concerns with too much arbitrary values, is it temporary only or is it what it is already? Is it possible to use the tailwind scale at most cases? Like use the closest scale to the arbitrary value?

Lastly, just code cleanup, formatting, and comments of parts for better readability and code quality.

2023-06-11 20:09 UTC, Lemon1903 reviewed
The code is running well and the carousels are working well already. My question is that the `ShowcaseCarousel` really looks like this? Or should it fill the whole container?
![image](https://github.com/PUP-The-Programmers-Guild/TPGWebsite/assets/99325731/8d5385e2-8551-4b18-a9c8-a684dca19595)

I have concerns with too much arbitrary values, is it temporary only or is it what it is already? Is it possible to use the tailwind scale at most cases? Like use the closest scale to the arbitrary value?

Lastly, just code cleanup, formatting, and comments of parts for better readability and code quality.

2023-06-12 02:30 UTC, Karmotrine commented
> The code is running well and the carousels are working well already. My question is that the `ShowcaseCarousel` really looks like this? Or should it fill the whole container? ![image](https://user-images.githubusercontent.com/99325731/244965542-8d5385e2-8551-4b18-a9c8-a684dca19595.png)
> 
> I have concerns with too much arbitrary values, is it temporary only or is it what it is already? Is it possible to use the tailwind scale at most cases? Like use the closest scale to the arbitrary value?
> 
> Lastly, just code cleanup, formatting, and comments of parts for better readability and code quality.

Based every value on Figma mockups, scales could work too but what we have so far is low fidelity designs, that's why I did not put much concern on width/height values.
<hr>

> I think this should be placed directly on the HTML element it should contain. Having one long line with tailwind is inevitable I guess if it really have many styles in it.

> `id` not used

Will refactor these

2023-06-12 04:40 UTC, Karmotrine commented
> The code is running well and the carousels are working well already. My question is that the `ShowcaseCarousel` really looks like this? Or should it fill the whole container? ![image](https://user-images.githubusercontent.com/99325731/244965542-8d5385e2-8551-4b18-a9c8-a684dca19595.png)

This can be worked on a separate branch feature. Something to do with `perView`  param of each carousel component.

2023-06-12 06:20 UTC, Lemon1903 requested changes
> Based every value on Figma mockups, scales could work too but what we have so far is low fidelity designs, that's why I did not put much concern on width/height values.

I see, so these values are temporary for now and will be changed when there are high fidelity wireframes already.

I have found no bugs from the code and the carousel is working perfectly already and the output looks good to me already. My only concern for now would be the in code formatting for code consistency like arrangement of tailwind utilities which can be done quickly with one prettier format, using template literals for `className` which acts like a normal string, and using arbitrary value even if there is a corresponding tailwind scale to it.

2023-06-14 17:34 UTC, Karmotrine commented
Repository can now be prettified by one command: `npm run prettify`
Template literals is not really possible especially in `.tsx` component props since it needs to be enclosed within curly braces.
Using Scales (using fractions) is usually dependent on zoom size

2023-06-15 06:49 UTC, Lemon1903 commented
The sizes of everything could be adjusted once high fidelity comes out and should not be focused for now. Then cleaning up the unecessary template literals on classnames could be fixed on another branch. Alright looks good to me!

2023-06-15 06:50 UTC, Lemon1903 approved these changes
The sizes of everything could be adjusted once high fidelity comes out and should not be focused for now. Then cleaning up the unecessary template literals on classnames could be fixed on another branch. Alright looks good to me!

2023-06-16 08:54 UTC, merged