Add files via upload
PUP-The-Programmers-Guild/TPGWebsite pull request #28
Opened 2023-09-02 07:31 UTC by Karmotrine

2023-09-13 11:39 UTC, Karmotrine commented
@Lemon1903 Follow up for approval

2023-09-13 12:03 UTC, Lemon1903 requested changes
May mga areas na di pa naayos. Please refer to the last review about the areas.

Clarification lang, diba dash siya sa branch name di underscores?

2023-09-13 12:05 UTC, Lemon1903 commented on README.md
> +IV. `[task-desc]` should be 2-3 words, connected by underscores / `_` , describing your task. Example would be: `latest_news_section`
diba das din to? di underscore?

2023-09-23 09:00 UTC, Lemon1903 requested changes

2023-09-29 14:14 UTC, Karmotrine commented on README.md
1.  Corrections 
> inserting a change directory command in "Getting Started" section

> the [task-desc] in line 68 should use dash and not underscores. Also it becomes inline with the refactor list item, so move it down to a new line

> the pull request in line 82 should be base:dev not base:main

> the fonts folder should not be expanded in "File Component Structure" section

Applied corrections for all of these.

> in line 92, what follows https://github.com/see?
Applied corrections for this, was meant to link it to specific sections of `README.md`



2. Suggestions to add:

> I think we should introduce shadcn also here? Maybe just mention it or add it in the "Learn More" section?

You mean `Radix-UI`? Anyways, I added information about `Radix-UI`

> the "File Component Structure" section should have a short description why is it structured like that I guess? Something like the folders under 'components' folder represents the pages separation, then under those folders are sections of that page, then lastly folders under those sections are components/utils/hooks/context for that section? Just only one context is enough to understand

Added this under `File Component Structure`

2023-09-29 14:15 UTC, Karmotrine commented
1.  Corrections 
> inserting a change directory command in "Getting Started" section

> the [task-desc] in line 68 should use dash and not underscores. Also it becomes inline with the refactor list item, so move it down to a new line

> the pull request in line 82 should be base:dev not base:main

> the fonts folder should not be expanded in "File Component Structure" section

Applied corrections for all of these.

> in line 92, what follows https://github.com/see?
Applied corrections for this, was meant to link it to specific sections of `README.md`



2. Suggestions to add:

> I think we should introduce shadcn also here? Maybe just mention it or add it in the "Learn More" section?

You mean `Radix-UI`? Anyways, I added information about `Radix-UI`

> the "File Component Structure" section should have a short description why is it structured like that I guess? Something like the folders under 'components' folder represents the pages separation, then under those folders are sections of that page, then lastly folders under those sections are components/utils/hooks/context for that section? Just only one context is enough to understand

Added this under `File Component Structure`

2023-09-30 04:15 UTC, Lemon1903 approved these changes
Just added a one commit fixing the formatting of one part only. Anyways, LGTM!

2023-09-30 04:16 UTC, merged