created a devskolar benefits section
PUP-The-Programmers-Guild/TPGWebsite pull request #35
Opened 2023-09-17 10:35 UTC by shaniassi

**Changes includes:**
- add: components/Devskolar/Benefits - new page. 
- modify: pages/register - imports a new component.

2023-09-17 23:38 UTC, Lemon1903 requested changes
Alright! The page loads the section without any errors. But the only problem is the section doesn't cover the whole screen's width. 

Here is the screenshot of the problem:
![image](https://github.com/PUP-The-Programmers-Guild/TPGWebsite/assets/99325731/d01975b1-d818-4012-b7e2-aab0aa2b7481)

Could you also organize the folder structure of the `components/Devskolar` folder as suggested in this [PR](https://github.com/PUP-The-Programmers-Guild/TPGWebsite/pull/31#pullrequestreview-1630087715)

Lastly, there are some utility classes that are not needed to be added since they are the default styling such as `items-start`, `content-start`, `justify-start`, `text-left`, etc.

As for my question, does your tailwindcss class names sort automatically without using a `.prettierrc` file? Since how your utility classes are sorted is the one I'm having before and it changed for I don't know reason. For example your `font-heading` (which is a custom tailwind configuration) comes after `text-center` and before `text-4xl`, but to me it comes first since it is a new added configuration. Weird, since it would cause inconsistent formatting in tailwind utility classes

2023-09-18 12:22 UTC, shaniassi commented
Thank you for your feedback; I'll make the necessary changes as soon as I can.  As for your question, I manually organized the classes instead of using Prettier. I'm still new to Tailwind so I didn't think about using Prettier.

2023-09-19 14:33 UTC, shaniassi commented
Good evening, I apologize for the late message🥲. I have completed the needed changes to this section, which are fixing the screen's width and removing some utility classes. I just want to know if do I need to create a new pull request to apply these changes?

2023-09-20 13:16 UTC, shaniassi commented
[Update]

**Changes includes:**
- fixed the screen's width
- removed some utility classes
- used Prettier to sort classes

2023-09-20 13:21 UTC, shaniassi commented
**Changes includes:**
 - Created a folder for benefits section 
`src/
└── components/
    └── Devskolar/ (devskolar page folder)
        ├── Hero/ (hero section folder)
        │   ├── Hero.module.css (components under hero section)
        │   ├── Hero.tsx
        │   └── HeroSteps.tsx
        ├── Process/ (process section folder)
        │   ├── Process.tsx (components under process section)
        │   └── ProcessBox.tsx
        └── Requirements/
            ├── RequirementBars.tsx
            └── Requirement.tsx
        │   └── ProcessBox.tsx
        └── Benefits
            └── Benefits.tsx`

2023-09-23 09:37 UTC, Lemon1903 requested changes
This branch now have merge conflicts since there are new changes that has been merged in the `dev` branch. Please resolve those conflicts first.

There are still some unresolved reviews from the last review, please check them out and tell me if you have any problems with that, thanks!

`w-1440` class is not registered in `tailwind.config.js` and it's not an arbitrary value also so it doesn't have any meaning. Just change it to `w-full` for now

The `Benefits.tsx` not having its own folder in Devskolar folder should be fine for now if Benefits section only have 1 file

2023-09-23 09:40 UTC, Lemon1903 commented on src/components/Devskolar/Benefits.tsx
> +      <div className="h-620 w-1440p relative inline-flex items-start justify-start gap-16 px-44 py-10 bg-[#8A8A8A] ">
> Also could you replace div tag here to section tag to make it semantically right, thanks!

### Update from the new changes:
`w-1440` class is not registered in `tailwind.config.js` and it's not an arbitrary value also so it doesn't have any meaning. Just change it to `w-full` for now

2023-09-24 15:51 UTC, shaniassi commented on src/components/Devskolar/Benefits.tsx
> +      <div className="h-620 w-1440p relative inline-flex items-start justify-start gap-16 px-44 py-10 bg-[#8A8A8A] ">
Oh, I see🥲. I'll take note of these, thank you!

2023-09-25 16:27 UTC, shaniassi commented
**Changes includes:** 

- Included the w-full and justify-center classes while replacing the div tag with a section tag.
- Replaced the SVG for the right arrow with the Phosphor icon for the right arrow.
-  Placed all four benefits into a single container.

2023-09-27 03:58 UTC, Lemon1903 approved these changes
I added some minor changes to the last commit, mainly just refactoring some unnecessary tw utilities and html tags. Anyways, LGTM!

2023-09-27 04:02 UTC, merged