Add contact section to the homepage
PUP-The-Programmers-Guild/TPGWebsite pull request #36
Opened 2023-09-17 10:37 UTC by xialuna

### Changes  includes:
- added a contact section to the home page
- removed  section className="min-h-screen" to the contact section
- import social media icons from phosphor icons

2023-09-18 00:46 UTC, Lemon1903 requested changes
Alright! The section loads very well in the homepage. The only thing that could be changed here is to extract the section from `pages/index.tsx` to a separate component in `components` folder. Please refer to how the `components\Home` are structured. For further details, refer to this [PR](https://github.com/PUP-The-Programmers-Guild/TPGWebsite/pull/31#pullrequestreview-1630087715)

2023-09-18 00:48 UTC, Lemon1903 commented on src/pages/index.tsx
> +        className="z-100 text-white"
You could remove the class `z-100` since there is no tailwind class for that

2023-09-20 07:22 UTC, xialuna commented
[Update]
### Changes includes:
- separate contacts from `index.tsx` and put it in the components folder
- remove z-100
- change size of icons and gap properties

2023-09-23 10:08 UTC, Lemon1903 requested changes
Ok it's nearly done, but there is one unresolved review from last review, please check it out. Let me know if there is a problem with that, thanks!

Then the final revision would be to move this code snippet in `index.tsx` into the `Contact.tsx` (please capitalize this as well for naming convention of component files).

from:
```tsx
<section
  className=" text-white"
  style={{
    background:
      "radial-gradient(100% 418.39% at 100% 100%, #343534 0%, #1E5C3F 33.33%, #409C49 66.67%, #FFEC5C 100%)",
  }}
>
  <Contacts />
</section>
```
to:
```tsx
<Contacts />
```
 So that the `Contacts.tsx` file would encapsulate all the code related to it.

2023-09-27 19:07 UTC, xialuna commented on src/pages/index.tsx
> +            </div>
[UPDATE]
### Changes Include
- Change naming convention of title from `contacts.tsx` to `Contacts.tsx`
- Reorganized the code within `Contacts.tsx` to encapsulate all related sections and styling.
- Used array of objects to manage the links and their respective icons.
- Used the map function to generate anchor elements for social media links

2023-09-27 19:08 UTC, xialuna commented
[UPDATE]
### Changes Include
- Change naming convention of title from `contacts.tsx` to `Contacts.tsx`
- Reorganized the code within `Contacts.tsx` to encapsulate all related sections and styling.
- Used array of objects to manage the links and their respective icons.
- Used the map function to generate anchor elements for social media links

2023-09-27 19:56 UTC, Lemon1903 approved these changes
Just added a commit that refactors the Home folder structure and imports. Anyways, LGTM!

2023-09-27 19:56 UTC, merged